### ISSUE TITLE
retrofit reactor adapter - exception

### ISSUE THREAD

**Issue by Kotlin-GDE** [JakeWharton/retrofit2-reactor-adapter#13]
hi

data class Person(var name: String,
                  var age: Int)

interface RouteService {
    @GET("/") fun findAll() : Flux<Person>
    @GET("/{name}") fun findByName(@Path("name") name: String) : Mono<Person>
}

val retrofit = Retrofit.Builder().apply {
        baseUrl("http://localhost:8888")
        addConverterFactory(GsonConverterFactory.create())
        addCallAdapterFactory(ReactorCallAdapterFactory.create())
    }.build()

    val restService = retrofit.create(RouteService::class.java)

    restService.findAll().log().subscribe()

when i exexcute i see this exception : 

Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 18 more 

whats wrong here ???

**Comment by JakeWharton** [comment]
This is a disagreement between the JSON and your data model, and isn't specific to your use of this library. I would recommend asking on StackOverflow with an example of your JSON, your data classes, and any configuration of Gson.
