### ISSUE TITLE
Question: Details of wow Flux works in this context

### ISSUE THREAD

**Issue by spencergibb** [JakeWharton/retrofit2-reactor-adapter#3]
Can you provide me with a few more details on how Flux works? In your tests you only get a single item from the server. Is it limited to that, or will it make more requests?

**Comment by JakeWharton** [comment]
Retrofit is fundamentally a single request/single response system so yes, there will only ever be a single emission. `Flux` is supported for type-system convenience should you already be using a `Flux`.

**Comment by spencergibb** [comment]
Thanks!
